# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wsAGzIQks61dl77VfeSLVccdw-rzitg
"""

print("hello world")

import numpy as np

print("---------")
print("|00000000|")
print("|00000000|")
print("|00000000|")
print("|00000000|")
print("|00000000|")
print("---------")

print("==============")
print("Привет")
print("Друг")
print("==============")

print("===============")
print("||           ||")
print("||           ||")
print("||  Привет   ||")
print("||  Друг     ||")
print("||           ||")
print("||           ||")
print("===============")

client = 'Петя'
pet = 'кот'
print(client)
print('and')
print(pet)

r = 'Red'
g = 'Green'
b = 'Blue'
print(r,b,g,r+g+b,b,g+b)

name = input("Введите имя:")
surname = input("Введите фамилию:")
city = input("Введите город:")
print("Your name:")
print(name, surname)
print("Your city:")
print(city)

name = input("Введите имя:")
p_file = input("введите путь")
print('C:/'+ name + '/docs/' + p_file)

